spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rates-service
              uri: http://rates-service
              predicates:
                - Path=/api/v1/quotation/{ticker}/price,/api/v1/quotation/{ticker}/quotes
            - id: orderbook-service
              uri: http://orderbook-service
              predicates:
                - Path=/api/v1/orderbook/{ticker}
            - id: trading-service
              uri: http://trading-service
              predicates:
                - Path=/api/v1/trade/order
            - id: instrument-service
              uri: http://instrument-service
              predicates:
                - Path=/api/v1/instrument