server:
  port: 10023

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    enable:
      jvm: true

engine:
  type: 'SINGLE_THREAD_ENGINE'
  initial-data-path: '/csv/initial-test-companies.csv'