<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.iflash</groupId>
    <artifactId>iflash</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>broker-management-service</module>
        <module>gateway-service</module>
        <module>matching-engine-service</module>
        <module>order-book-service</module>
        <module>rates-service</module>
        <module>settlement-service</module>
        <module>trading-service</module>
        <module>iflash-engine</module>

        <module>helpers/iflash-platform</module>
        <module>helpers/trading-simulator</module>
        <module>helpers/broker-platform</module>
    </modules>

    <dependencyManagement>

    </dependencyManagement>

    <properties>
        <java.version>25</java.version>
    </properties>
</project>
